apiVersion: kubeadm.k8s.io/v1beta2
kind: ClusterConfiguration
imageRepository: {{ kubernetes_container_registry }}
kubernetesVersion: {{ kubernetes_semver }}
---
apiVersion: kubeadm.k8s.io/v1beta2
kind: InitConfiguration
