---
- import_tasks: redhat.yml
  when: ansible_os_family == "RedHat"

- name: disable firewalld
  systemd:
    name: firewalld
    enabled: false
    state: stopped

- name: disable selinux
  selinux: 
    state: disabled
    policy: targeted

- name: disable swap space
  lineinfile:
    path: /etc/fstab
    regexp: ^/dev/mapper/centos-swap .*
    state: absent

- name: Ensure overlay module is present
  modprobe:
    name: overlay
    state: present

- name: Ensure br_netfilter module is present
  modprobe:
    name: br_netfilter
    state: present

- name: Persist required kernel modules
  copy:
    content: |
      overlay
      br_netfilter
    dest: /etc/modules-load.d/kubernetes.conf

- name: Ensure net.ipv4.ip_forward sysctl is present
  sysctl:
    name: net.ipv4.ip_forward
    value: "1"
    state: present
    sysctl_set: yes
    reload: yes
    sysctl_file: "{{ sysctl_conf_file }}"

- name: Ensure net.bridge.bridge-nf-call-iptables sysctl is present
  sysctl:
    name: net.bridge.bridge-nf-call-iptables
    value: "1"
    state: present
    sysctl_set: yes
    reload: yes
    sysctl_file: "{{ sysctl_conf_file }}"

- name: Ensure net.bridge.bridge-nf-call-ip6tables sysctl is present
  sysctl:
    name: net.bridge.bridge-nf-call-ip6tables
    value: "1"
    state: present
    sysctl_set: yes
    reload: yes
    sysctl_file: "{{ sysctl_conf_file }}"
